name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traffic_data_test
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1

      - name: Install Backend Dependencies
        run: |
          cd backend
          bundle install

      - name: Setup Database
        run: |
          cd backend
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create db:schema:load

      - name: Run RSpec tests
        run: |
          cd backend
          bundle exec rspec
        
